module SkelPetit = struct

(* OCaml module generated by the BNF converter *)

open AbsPetit

type result = string

let failure x = failwith "Undefined case." (* x discarded *)

let rec transIdent (x : ident) : result = match x with
    Ident string -> failure x


and transStm (x : stm) : result = match x with
    Ass (ident, exp) -> failure x
  | Con (stm0, stm) -> failure x
  | For (exp, stm) -> failure x


and transExp (x : exp) : result = match x with
    Zer  -> failure x
  | Var ident -> failure x
  | Suc exp -> failure x



end
